USE QLSVNhom
GO

-- 1. SP Login
CREATE PROCEDURE SP_LOGIN_NHANVIEN
    @MANV VARCHAR(20),
    @MATKHAU VARCHAR(100) 
AS
BEGIN
    SELECT MANV, HOTEN 
    FROM NHANVIEN 
    WHERE MANV = @MANV AND MATKHAU = HASHBYTES('SHA1', CONVERT(VARCHAR, @MATKHAU))
END
GO

-- 2. SP select class
CREATE PROCEDURE SP_SEL_LOP_BY_NV
    @MANV VARCHAR(20)
AS
BEGIN
    SELECT l.MALOP, l.TENLOP
    FROM LOP l 
    WHERE l.MANV = @MANV
END
GO
